
library(ggplot2)
#setwd('C:/Users/yashr/Documents/Random Projects/DiscordScraper/plots')



make_user_data <- function(){
  if(!exists("get_intro_data", mode = "function"))
    source("loadIntroData.R")
  
  data = get_intro_data()
  #reads unique majors and the category they fit in
  #categories were generated by hand because the dataset is sufficently small
  majors = read.csv("./lib/categorized_majors.csv")
  
  #combines major categories and the rest of the dataset
  users = merge(x=data, y=majors, by = "Major", all.x = TRUE)
  
  return(users)
}



#' creates and returns plots
#' @param type_str the type of plot to make
#' @noRd
make_plot <- function(type_str){
  
  users <- make_user_data()
  
  
  
  
  if(identical(type_str, "major")){
    major_plot <- ggplot(data=users, aes(x=Category)) + 
      geom_bar(aes(y=..count..))
    return(major_plot)
  }
  
  if(identical(type_str, "year/found")){
    year_and_found_plot <- ggplot(data=users, aes(x=Year)) +
      geom_bar(aes(y=..count.., fill=HowFound)) +
 #     scale_fill_brewer(palette = "Set1")
      scale_fill_manual(values = c("#ff0000", "#6666ff", "#009933", "orange", "#9933ff"))
    return(year_and_found_plot)
  }
  
  
  
}





