
library(ggplot2)
setwd('C:/Users/yashr/Documents/Random Projects/DiscordScraper/plots')

#reads unique majors and the category they fit in
#categories were generated by hand because the dataset is sufficently small
majors = read.csv("./lib/categorized_majors.csv")

#combines major categories and the rest of the dataset
users = merge(x=data, y=majors, by = "Major", all.x = TRUE)




#creates plots
year_and_major_plot <- ggplot(data=users, aes(x=Year)) + 
                        geom_bar(aes(y=..count.., fill=Category))

major_plot <- ggplot(data=users, aes(x=Category)) + 
                        geom_bar(aes(y=..count..))

year_and_found_plot <- ggplot(data=users, aes(x=Year)) +
                        geom_bar(aes(y=..count.., fill=HowFound)) +
                        scale_fill_brewer(palette = "Set1")
